"""The number gate must refuse a faked or absent number.

Every quantity the paper quotes is a macro generated by bin/regen.py from
committed data. These tests plant defects at that boundary and assert the gate
notices: a hand-typed number must not survive regeneration, an aggregation over
nothing must render NA and never 0, and a headline recall figure must be refused
while the census is not a complete enumeration. A suite that only ran regen once
and eyeballed it would certify that the script ran, not that a wrong number cannot
slip through.
"""
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
REGEN = REPO / "bin" / "regen.py"
sys.path.insert(0, str(REPO / "src"))


def _regen(out: pathlib.Path):
    r = subprocess.run([sys.executable, str(REGEN), "--tex", str(out)],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    return out.read_text()


def _macro(text: str, name: str):
    m = re.search(r"\\newcommand\{\\%s\}\{([^}]*)\}" % re.escape(name), text)
    return m.group(1) if m else None


def test_regen_is_deterministic(tmp_path):
    a = _regen(tmp_path / "a.tex")
    b = _regen(tmp_path / "b.tex")
    assert a == b, "regen is not deterministic over unchanged committed data"


def test_a_hand_typed_number_does_not_survive(tmp_path):
    # The generated tool count is derived from data/tools.toml. Plant a wrong
    # value and regenerate over it: the fake must not survive.
    out = tmp_path / "numbers.tex"
    good = _regen(out)
    truth = _macro(good, "nTools")
    assert truth is not None
    faked = good.replace("{\\nTools}{%s}" % truth, "{\\nTools}{999}")
    out.write_text(faked)
    assert "999" in out.read_text()
    regrown = _regen(out)
    assert _macro(regrown, "nTools") == truth
    assert "{\\nTools}{999}" not in regrown, "a hand-typed number survived regeneration"


def test_na_over_nothing_is_not_zero():
    from corpus.util.na import Rate, mean, NA
    empty = Rate(0, 0, "nothing to divide")
    assert empty.value is None, "an undefined rate reported 0.0 as if measured"
    assert NA in empty.render()
    assert "(n=0)" in empty.render()
    assert mean([], "empty").value is None
    # A real zero is distinct from NA: a rate of 0 over a real denominator stays 0.
    real_zero = Rate(0, 5, "measured zero")
    assert real_zero.value == 0.0
    assert NA not in real_zero.render()


def test_headline_is_refused_while_census_is_expanded():
    r = subprocess.run([sys.executable, str(REGEN), "--headline"],
                       capture_output=True, text=True)
    assert r.returncode == 1, "the headline gate did not refuse"
    assert "REFUSING" in r.stdout
    assert "CLS-3" in r.stdout, "the refusal did not name the census-completeness gate"
